"""Reusable ChArUco and chessboard calibration helpers."""

from __future__ import annotations

import json
import shutil
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
from typing import Callable, Dict, List, Optional, Sequence, Tuple

import cv2
import numpy as np


IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"}
MIN_CORNERS_PER_IMAGE = 6
MIN_CALIBRATION_IMAGES = 5
AUTO_OUTLIER_MIN_IMAGES = 10
AUTO_OUTLIER_SIGMA = 3.0
AUTO_OUTLIER_MAX_FRACTION = 0.20
FISHEYE_NATURAL_FOCAL_SCALE = 1.0
FISHEYE_WIDE_FOCAL_SCALE = 0.70


@dataclass(frozen=True)
class BoardConfig:
    """Physical settings for a ChArUco or traditional chessboard."""

    dictionary_name: str = "DICT_5X5_100"
    squares_vertical: int = 9
    squares_horizontal: int = 14
    square_length: float = 0.020
    marker_length: float = 0.015
    legacy_pattern: bool = False
    pattern_type: str = "charuco"

    def validate(self) -> None:
        if self.pattern_type not in {"charuco", "chessboard"}:
            raise ValueError(f"不支持的标定板类型：{self.pattern_type}")
        if self.squares_vertical < 2 or self.squares_horizontal < 2:
            unit = "内角点数量" if self.pattern_type == "chessboard" else "方格数量"
            raise ValueError(f"标定板横向和纵向{unit}必须至少为 2。")
        if self.square_length <= 0:
            raise ValueError("方格边长必须大于 0。")
        if self.pattern_type == "charuco":
            if not hasattr(cv2.aruco, self.dictionary_name):
                raise ValueError(f"OpenCV 不支持 ArUco 字典：{self.dictionary_name}")
            if self.marker_length <= 0:
                raise ValueError("ArUco 标记边长必须大于 0。")
            if self.marker_length >= self.square_length:
                raise ValueError("ArUco 标记边长必须小于棋盘方格边长。")

    @property
    def dictionary_id(self) -> int:
        self.validate()
        return int(getattr(cv2.aruco, self.dictionary_name))


@dataclass
class DetectionResult:
    marker_corners: Sequence[np.ndarray]
    marker_ids: Optional[np.ndarray]
    charuco_corners: Optional[np.ndarray]
    charuco_ids: Optional[np.ndarray]
    pattern_type: str = "charuco"
    pattern_size: Optional[Tuple[int, int]] = None

    @property
    def marker_count(self) -> int:
        return 0 if self.marker_ids is None else int(len(self.marker_ids))

    @property
    def corner_count(self) -> int:
        return 0 if self.charuco_ids is None else int(len(self.charuco_ids))

    @property
    def corners(self) -> Optional[np.ndarray]:
        """Detected calibration corners (legacy ChArUco name kept compatible)."""

        return self.charuco_corners

    @property
    def ids(self) -> Optional[np.ndarray]:
        """Point indices matching the calibration-board object points."""

        return self.charuco_ids


def create_charuco_board(config: BoardConfig):
    """Create a board with OpenCV's required (horizontal, vertical) ordering."""

    config.validate()
    dictionary = cv2.aruco.getPredefinedDictionary(config.dictionary_id)
    board_size = (config.squares_horizontal, config.squares_vertical)

    if hasattr(cv2.aruco, "CharucoBoard"):
        board = cv2.aruco.CharucoBoard(
            board_size,
            config.square_length,
            config.marker_length,
            dictionary,
        )
    else:
        board = cv2.aruco.CharucoBoard_create(
            config.squares_horizontal,
            config.squares_vertical,
            config.square_length,
            config.marker_length,
            dictionary,
        )

    # OpenCV 4.6 changed the ChArUco pattern for boards with an even number
    # of rows. Keep this optional for boards generated by older OpenCV versions.
    if config.legacy_pattern and hasattr(board, "setLegacyPattern"):
        board.setLegacyPattern(True)
    return board


def create_detector_parameters():
    if hasattr(cv2.aruco, "DetectorParameters"):
        return cv2.aruco.DetectorParameters()
    return cv2.aruco.DetectorParameters_create()


def get_board_corners(board) -> np.ndarray:
    if hasattr(board, "getChessboardCorners"):
        return np.asarray(board.getChessboardCorners(), dtype=np.float64)
    return np.asarray(board.chessboardCorners, dtype=np.float64)


def detect_charuco(image: np.ndarray, config: BoardConfig) -> DetectionResult:
    """Detect ArUco markers and interpolate ChArUco corners in one image."""

    if image is None or image.size == 0:
        raise ValueError("输入图像为空。")

    board = create_charuco_board(config)
    dictionary = cv2.aruco.getPredefinedDictionary(config.dictionary_id)
    parameters = create_detector_parameters()
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) if image.ndim == 3 else image

    # OpenCV 5 moved the procedural ArUco functions onto detector classes.
    if not hasattr(cv2.aruco, "detectMarkers") and hasattr(
        cv2.aruco,
        "CharucoDetector",
    ):
        detector = cv2.aruco.CharucoDetector(board)
        charuco_corners, charuco_ids, marker_corners, marker_ids = (
            detector.detectBoard(gray)
        )
        if charuco_ids is None or len(charuco_ids) == 0:
            charuco_corners, charuco_ids = None, None
        else:
            charuco_corners = np.asarray(charuco_corners, dtype=np.float32).reshape(
                -1,
                1,
                2,
            )
            charuco_ids = np.asarray(charuco_ids, dtype=np.int32).reshape(-1, 1)
        if marker_ids is not None:
            marker_ids = np.asarray(marker_ids, dtype=np.int32).reshape(-1, 1)
        return DetectionResult(
            marker_corners,
            marker_ids,
            charuco_corners,
            charuco_ids,
            "charuco",
        )

    marker_corners, marker_ids, rejected = cv2.aruco.detectMarkers(
        gray,
        dictionary,
        parameters=parameters,
    )

    if marker_ids is None or len(marker_ids) == 0:
        return DetectionResult(marker_corners, None, None, None, "charuco")

    try:
        refined_corners, refined_ids, _, _ = cv2.aruco.refineDetectedMarkers(
            gray,
            board,
            marker_corners,
            marker_ids,
            rejected,
            parameters=parameters,
        )
        if refined_ids is not None:
            marker_corners, marker_ids = refined_corners, refined_ids
    except cv2.error:
        # Marker refinement can fail on strongly distorted edge regions. The
        # initially detected markers are still useful for interpolation.
        pass

    retval, charuco_corners, charuco_ids = cv2.aruco.interpolateCornersCharuco(
        marker_corners,
        marker_ids,
        gray,
        board,
    )

    if not retval or charuco_ids is None:
        charuco_corners, charuco_ids = None, None

    return DetectionResult(
        marker_corners,
        marker_ids,
        charuco_corners,
        charuco_ids,
        "charuco",
    )


def detect_chessboard(image: np.ndarray, config: BoardConfig) -> DetectionResult:
    """Detect all inner corners of a traditional black-and-white chessboard."""

    config.validate()
    if image is None or image.size == 0:
        raise ValueError("输入图像为空。")

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) if image.ndim == 3 else image
    pattern_size = (config.squares_horizontal, config.squares_vertical)
    flags = cv2.CALIB_CB_NORMALIZE_IMAGE
    if hasattr(cv2, "CALIB_CB_EXHAUSTIVE"):
        flags |= cv2.CALIB_CB_EXHAUSTIVE
    if hasattr(cv2, "CALIB_CB_ACCURACY"):
        flags |= cv2.CALIB_CB_ACCURACY
    found, corners = cv2.findChessboardCornersSB(gray, pattern_size, flags=flags)
    if not found or corners is None:
        return DetectionResult([], None, None, None, "chessboard", pattern_size)

    corners = np.asarray(corners, dtype=np.float32).reshape(-1, 1, 2)
    ids = np.arange(len(corners), dtype=np.int32).reshape(-1, 1)
    return DetectionResult(
        [],
        None,
        corners,
        ids,
        "chessboard",
        pattern_size,
    )


def detect_calibration_board(
    image: np.ndarray,
    config: BoardConfig,
) -> DetectionResult:
    """Detect the board type selected in ``config``."""

    if config.pattern_type == "chessboard":
        return detect_chessboard(image, config)
    return detect_charuco(image, config)


def create_chessboard_object_points(config: BoardConfig) -> np.ndarray:
    """Return row-major 3-D points for chessboard inner corners."""

    config.validate()
    points = np.zeros(
        (config.squares_horizontal * config.squares_vertical, 3),
        dtype=np.float64,
    )
    points[:, :2] = np.mgrid[
        0 : config.squares_horizontal,
        0 : config.squares_vertical,
    ].T.reshape(-1, 2)
    points *= config.square_length
    return points


def draw_detection(image: np.ndarray, detection: DetectionResult) -> np.ndarray:
    annotated = image.copy()
    if detection.pattern_type == "chessboard":
        if detection.corners is not None and detection.pattern_size is not None:
            cv2.drawChessboardCorners(
                annotated,
                detection.pattern_size,
                detection.corners,
                True,
            )
        return annotated
    if detection.marker_ids is not None:
        cv2.aruco.drawDetectedMarkers(
            annotated,
            detection.marker_corners,
            detection.marker_ids,
        )
    if detection.charuco_ids is not None:
        cv2.aruco.drawDetectedCornersCharuco(
            annotated,
            detection.charuco_corners,
            detection.charuco_ids,
            (0, 255, 0),
        )
    return annotated


def _save_detection_image(
    image: np.ndarray,
    detection: DetectionResult,
    output_path: Path,
    status: str,
    details: str = "",
) -> bool:
    """Save a full-resolution detection visualization with a status banner."""

    annotated = draw_detection(image, detection)
    summary = (
        f"{status}  markers={detection.marker_count}  "
        f"corners={detection.corner_count}"
    )
    if details:
        summary += f"  {details}"

    font_scale = max(0.65, annotated.shape[1] / 1600.0)
    thickness = max(2, int(round(annotated.shape[1] / 1000.0)))
    (text_width, text_height), baseline = cv2.getTextSize(
        summary,
        cv2.FONT_HERSHEY_SIMPLEX,
        font_scale,
        thickness,
    )
    colors = {
        "USED": (30, 190, 30),
        "CANDIDATE": (30, 190, 190),
        "OUTLIER": (20, 80, 255),
        "SKIPPED": (30, 30, 220),
    }
    color = colors.get(status, (255, 255, 255))
    cv2.rectangle(
        annotated,
        (0, 0),
        (min(annotated.shape[1], text_width + 24), text_height + baseline + 22),
        (0, 0, 0),
        -1,
    )
    cv2.putText(
        annotated,
        summary,
        (12, text_height + 10),
        cv2.FONT_HERSHEY_SIMPLEX,
        font_scale,
        color,
        thickness,
        cv2.LINE_AA,
    )
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    return bool(cv2.imwrite(str(output_path), annotated))


def list_calibration_images(images_dir: Path) -> List[Path]:
    images_dir = Path(images_dir)
    if not images_dir.exists():
        return []
    return sorted(
        path
        for path in images_dir.iterdir()
        if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS
    )


def archive_calibration_images(
    images_dir: Path,
    archive_root: Path,
    batch_name: Optional[str] = None,
) -> Tuple[Optional[Path], List[str]]:
    """Move the active calibration images into a recoverable batch archive."""

    image_paths = list_calibration_images(images_dir)
    if not image_paths:
        return None, []

    base_name = batch_name or datetime.now().strftime("%Y%m%d_%H%M%S_%f")[:-3]
    archive_dir = Path(archive_root) / base_name
    suffix = 1
    while archive_dir.exists():
        archive_dir = Path(archive_root) / f"{base_name}_{suffix}"
        suffix += 1
    archive_dir.mkdir(parents=True, exist_ok=False)

    archived_names: List[str] = []
    try:
        for image_path in image_paths:
            shutil.move(str(image_path), str(archive_dir / image_path.name))
            archived_names.append(image_path.name)
    except Exception:
        for archived_name in reversed(archived_names):
            archived_path = archive_dir / archived_name
            original_path = Path(images_dir) / archived_name
            if archived_path.exists() and not original_path.exists():
                shutil.move(str(archived_path), str(original_path))
        if archive_dir.exists() and not any(archive_dir.iterdir()):
            archive_dir.rmdir()
        raise
    return archive_dir, archived_names


def _collect_observations(
    images_dir: Path,
    config: BoardConfig,
    progress: Optional[Callable[[str], None]] = None,
    detected_images_dir: Optional[Path] = None,
) -> Tuple[
    List[np.ndarray],
    List[np.ndarray],
    Tuple[int, int],
    List[str],
    List[str],
    List[str],
]:
    image_paths = list_calibration_images(images_dir)
    if not image_paths:
        raise RuntimeError(f"标定图片目录为空：{images_dir}")

    all_corners: List[np.ndarray] = []
    all_ids: List[np.ndarray] = []
    used_images: List[str] = []
    skipped_images: List[str] = []
    detected_images: List[str] = []
    image_size: Optional[Tuple[int, int]] = None

    if detected_images_dir is not None:
        detected_images_dir = Path(detected_images_dir)
        detected_images_dir.mkdir(parents=True, exist_ok=True)
        if progress:
            progress(f"检测识别图像将保存到：{detected_images_dir}")

    for index, image_path in enumerate(image_paths, start=1):
        if progress:
            progress(f"检测图片 {index}/{len(image_paths)}：{image_path.name}")

        image = cv2.imread(str(image_path))
        if image is None:
            skipped_images.append(f"{image_path.name}（无法读取）")
            continue

        current_size = (int(image.shape[1]), int(image.shape[0]))
        if image_size is None:
            image_size = current_size
        elif current_size != image_size:
            skipped_images.append(
                f"{image_path.name}（分辨率 {current_size} 与 {image_size} 不一致）"
            )
            continue

        detection = detect_calibration_board(image, config)
        accepted = detection.corner_count >= MIN_CORNERS_PER_IMAGE

        if detected_images_dir is not None:
            detected_path = detected_images_dir / image_path.name
            status = "CANDIDATE" if accepted else "SKIPPED"
            if _save_detection_image(
                image,
                detection,
                detected_path,
                status,
            ):
                detected_images.append(detected_path.name)
            elif progress:
                progress(f"警告：无法保存检测识别图像：{detected_path}")

        if detection.corner_count < MIN_CORNERS_PER_IMAGE:
            skipped_images.append(
                f"{image_path.name}（仅检测到 {detection.corner_count} 个角点）"
            )
            continue

        all_corners.append(np.asarray(detection.corners, dtype=np.float32))
        all_ids.append(np.asarray(detection.ids, dtype=np.int32))
        used_images.append(image_path.name)

    if image_size is None:
        raise RuntimeError("没有可读取的标定图片。")
    if len(used_images) < MIN_CALIBRATION_IMAGES:
        raise RuntimeError(
            f"有效标定图片只有 {len(used_images)} 张，至少需要 "
            f"{MIN_CALIBRATION_IMAGES} 张；建议拍摄 15～25 张。"
        )

    return (
        all_corners,
        all_ids,
        image_size,
        used_images,
        skipped_images,
        detected_images,
    )


def _mean_reprojection_error(
    model: str,
    object_points: Sequence[np.ndarray],
    image_points: Sequence[np.ndarray],
    rvecs: Sequence[np.ndarray],
    tvecs: Sequence[np.ndarray],
    camera_matrix: np.ndarray,
    distortion: np.ndarray,
) -> Tuple[float, List[float]]:
    errors: List[float] = []
    for object_point, image_point, rvec, tvec in zip(
        object_points,
        image_points,
        rvecs,
        tvecs,
    ):
        if model == "fisheye":
            projected, _ = cv2.fisheye.projectPoints(
                object_point,
                rvec,
                tvec,
                camera_matrix,
                distortion,
            )
        else:
            projected, _ = cv2.projectPoints(
                object_point,
                rvec,
                tvec,
                camera_matrix,
                distortion,
            )

        point_count = max(int(len(projected)), 1)
        error = cv2.norm(image_point, projected, cv2.NORM_L2) / point_count
        errors.append(float(error))

    return (float(np.mean(errors)) if errors else 0.0), errors


def _calibrate_observations(
    model: str,
    corners: Sequence[np.ndarray],
    ids: Sequence[np.ndarray],
    object_points: Sequence[np.ndarray],
    image_points: Sequence[np.ndarray],
    board,
    image_size: Tuple[int, int],
    pattern_type: str,
):
    """Run one camera-calibration pass for the selected observations."""

    if model == "fisheye":
        camera_matrix = np.zeros((3, 3), dtype=np.float64)
        distortion = np.zeros((4, 1), dtype=np.float64)
        recompute_flag = getattr(
            cv2.fisheye,
            "CALIB_RECOMPUTE_EXTRINSIC",
            getattr(cv2, "CALIB_RECOMPUTE_EXTRINSIC", 0),
        )
        fix_skew_flag = getattr(
            cv2.fisheye,
            "CALIB_FIX_SKEW",
            getattr(cv2, "CALIB_FIX_SKEW", 0),
        )
        flags = recompute_flag | fix_skew_flag
        criteria = (
            cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_MAX_ITER,
            100,
            1e-7,
        )
        return cv2.fisheye.calibrate(
            object_points,
            image_points,
            image_size,
            camera_matrix,
            distortion,
            flags=flags,
            criteria=criteria,
        )

    if pattern_type == "charuco" and hasattr(
        cv2.aruco,
        "calibrateCameraCharuco",
    ):
        return cv2.aruco.calibrateCameraCharuco(
            corners,
            ids,
            board,
            image_size,
            None,
            None,
        )
    return cv2.calibrateCamera(
        [np.asarray(points, dtype=np.float32) for points in object_points],
        [np.asarray(points, dtype=np.float32) for points in image_points],
        image_size,
        None,
        None,
    )


def _robust_outlier_threshold(errors: Sequence[float]) -> Tuple[float, float, float]:
    """Return threshold, median and scaled MAD for per-view errors."""

    values = np.asarray(errors, dtype=np.float64)
    median = float(np.median(values))
    mad = float(np.median(np.abs(values - median)))
    robust_sigma = 1.4826 * mad
    threshold = max(
        median + AUTO_OUTLIER_SIGMA * robust_sigma,
        median * 2.0,
    )
    return float(threshold), median, float(robust_sigma)


def _rewrite_final_detection_images(
    images_dir: Path,
    detected_images_dir: Path,
    config: BoardConfig,
    final_errors: Dict[str, float],
    outlier_errors: Dict[str, float],
    outlier_threshold: Optional[float],
    progress: Optional[Callable[[str], None]] = None,
) -> None:
    """Rewrite candidate visualizations with their final calibration status."""

    for image_path in list_calibration_images(images_dir):
        image = cv2.imread(str(image_path))
        if image is None:
            continue
        detection = detect_calibration_board(image, config)
        if image_path.name in outlier_errors:
            status = "OUTLIER"
            details = f"error={outlier_errors[image_path.name]:.5f}"
            if outlier_threshold is not None:
                details += f" threshold={outlier_threshold:.5f}"
        elif image_path.name in final_errors:
            status = "USED"
            details = f"error={final_errors[image_path.name]:.5f}"
        else:
            status = "SKIPPED"
            details = "insufficient corners"

        output_path = Path(detected_images_dir) / image_path.name
        if not _save_detection_image(
            image,
            detection,
            output_path,
            status,
            details,
        ) and progress:
            progress(f"警告：无法更新检测识别图像：{output_path}")


def build_colmap_camera_line(
    model: str,
    camera_matrix: np.ndarray,
    distortion: np.ndarray,
) -> str:
    fx = float(camera_matrix[0, 0])
    fy = float(camera_matrix[1, 1])
    cx = float(camera_matrix[0, 2])
    cy = float(camera_matrix[1, 2])
    coefficients = np.asarray(distortion, dtype=float).reshape(-1)

    if model == "fisheye":
        values = list(coefficients[:4])
        while len(values) < 4:
            values.append(0.0)
        return "OPENCV_FISHEYE: " + ", ".join(
            f"{value:.12g}" for value in (fx, fy, cx, cy, *values)
        )

    values = list(coefficients[:5])
    while len(values) < 5:
        values.append(0.0)
    k1, k2, p1, p2, _k3 = values
    return "OPENCV: " + ", ".join(
        f"{value:.12g}" for value in (fx, fy, cx, cy, k1, k2, p1, p2)
    )


def calibrate_from_directory(
    images_dir: Path,
    config: BoardConfig,
    model: str,
    output_path: Path,
    progress: Optional[Callable[[str], None]] = None,
    detected_images_dir: Optional[Path] = None,
    auto_reject_outliers: bool = True,
) -> Dict[str, object]:
    """Calibrate a fisheye or pinhole camera and save a JSON result."""

    if model not in {"fisheye", "pinhole"}:
        raise ValueError(f"不支持的相机模型：{model}")
    config.validate()

    (
        corners,
        ids,
        image_size,
        used_images,
        skipped_images,
        detected_images,
    ) = _collect_observations(
        Path(images_dir),
        config,
        progress,
        detected_images_dir,
    )
    if config.pattern_type == "charuco":
        board = create_charuco_board(config)
        board_corners = get_board_corners(board)
    else:
        board = None
        board_corners = create_chessboard_object_points(config)

    object_points = [
        board_corners[image_ids.reshape(-1)]
        .reshape(-1, 1, 3)
        .astype(np.float64)
        for image_ids in ids
    ]
    image_points = [
        image_corners.reshape(-1, 1, 2).astype(np.float64)
        for image_corners in corners
    ]

    if progress:
        progress(f"第一遍使用 {len(used_images)} 张有效图片计算相机参数……")

    rms, camera_matrix, distortion, rvecs, tvecs = _calibrate_observations(
        model,
        corners,
        ids,
        object_points,
        image_points,
        board,
        image_size,
        config.pattern_type,
    )
    initial_mean_error, initial_per_view_errors = _mean_reprojection_error(
        model,
        object_points,
        image_points,
        rvecs,
        tvecs,
        camera_matrix,
        distortion,
    )

    initial_rms = float(rms)
    initial_used_images = list(used_images)
    outlier_threshold: Optional[float] = None
    outlier_median: Optional[float] = None
    outlier_robust_sigma: Optional[float] = None
    rejected_indices: List[int] = []

    if auto_reject_outliers and len(used_images) >= AUTO_OUTLIER_MIN_IMAGES:
        (
            outlier_threshold,
            outlier_median,
            outlier_robust_sigma,
        ) = _robust_outlier_threshold(initial_per_view_errors)
        rejected_indices = [
            index
            for index, error in enumerate(initial_per_view_errors)
            if error > outlier_threshold
        ]
        maximum_rejected = max(
            1,
            int(np.floor(len(used_images) * AUTO_OUTLIER_MAX_FRACTION)),
        )
        maximum_rejected = min(
            maximum_rejected,
            len(used_images) - MIN_CALIBRATION_IMAGES,
        )
        rejected_indices = sorted(
            rejected_indices,
            key=lambda index: initial_per_view_errors[index],
            reverse=True,
        )[:maximum_rejected]

    outlier_images = [
        {
            "name": used_images[index],
            "initial_error": float(initial_per_view_errors[index]),
        }
        for index in rejected_indices
    ]

    if rejected_indices:
        rejected_set = set(rejected_indices)
        retained_indices = [
            index for index in range(len(used_images)) if index not in rejected_set
        ]
        used_images = [used_images[index] for index in retained_indices]
        corners = [corners[index] for index in retained_indices]
        ids = [ids[index] for index in retained_indices]
        object_points = [object_points[index] for index in retained_indices]
        image_points = [image_points[index] for index in retained_indices]

        for outlier in outlier_images:
            skipped_images.append(
                f"{outlier['name']}（自动剔除：初次单图误差 "
                f"{outlier['initial_error']:.6f} px，阈值 "
                f"{outlier_threshold:.6f} px）"
            )

        if progress:
            names = "、".join(str(item["name"]) for item in outlier_images)
            progress(
                f"自动发现 {len(outlier_images)} 张误差离群图并剔除：{names}；"
                f"使用剩余 {len(used_images)} 张重新标定……"
            )

        rms, camera_matrix, distortion, rvecs, tvecs = _calibrate_observations(
            model,
            corners,
            ids,
            object_points,
            image_points,
            board,
            image_size,
            config.pattern_type,
        )

    mean_error, per_view_errors = _mean_reprojection_error(
        model,
        object_points,
        image_points,
        rvecs,
        tvecs,
        camera_matrix,
        distortion,
    )

    if detected_images_dir is not None:
        final_errors = dict(zip(used_images, per_view_errors))
        outlier_errors = {
            str(item["name"]): float(item["initial_error"])
            for item in outlier_images
        }
        _rewrite_final_detection_images(
            Path(images_dir),
            Path(detected_images_dir),
            config,
            final_errors,
            outlier_errors,
            outlier_threshold,
            progress,
        )

    colmap = build_colmap_camera_line(model, camera_matrix, distortion)

    result: Dict[str, object] = {
        "model": model,
        "created_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "image_size": [int(image_size[0]), int(image_size[1])],
        "rms": float(rms),
        "mean_reprojection_error": float(mean_error),
        "per_view_errors": per_view_errors,
        "initial_rms": initial_rms,
        "initial_mean_reprojection_error": float(initial_mean_error),
        "initial_images_used": len(initial_used_images),
        "auto_reject_outliers": bool(auto_reject_outliers),
        "outlier_threshold": outlier_threshold,
        "outlier_error_median": outlier_median,
        "outlier_robust_sigma": outlier_robust_sigma,
        "outlier_images": outlier_images,
        "images_used": len(used_images),
        "used_images": used_images,
        "skipped_images": skipped_images,
        "detected_images_dir": (
            str(Path(detected_images_dir)) if detected_images_dir is not None else ""
        ),
        "detected_images": detected_images,
        "board": asdict(config),
        "K": np.asarray(camera_matrix).tolist(),
        "D": np.asarray(distortion).tolist(),
        "rvecs": [np.asarray(value).tolist() for value in rvecs],
        "tvecs": [np.asarray(value).tolist() for value in tvecs],
        "colmap": colmap,
    }

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as file:
        json.dump(result, file, ensure_ascii=False, indent=2)

    if progress:
        progress(f"标定参数已保存：{output_path}")
    return result


def load_calibration(path: Path) -> Dict[str, object]:
    path = Path(path)
    with path.open("r", encoding="utf-8") as file:
        result = json.load(file)

    if "K" not in result or "D" not in result:
        raise ValueError(f"参数文件缺少 K 或 D：{path}")
    if "model" not in result:
        result["model"] = "fisheye" if "fisheye" in path.name else "pinhole"
    return result


def fisheye_focal_scale_for_balance(balance: float) -> float:
    """Blend from the reference-like natural view to the wider legacy view.

    ``balance=0`` keeps the calibrated focal length (the same projection used
    by the reference project). ``balance=1`` keeps the previous 0.70-wide
    projection for users who prefer maximum field of view.
    """

    selected_balance = float(np.clip(balance, 0.0, 1.0))
    return float(
        FISHEYE_NATURAL_FOCAL_SCALE
        + selected_balance
        * (FISHEYE_WIDE_FOCAL_SCALE - FISHEYE_NATURAL_FOCAL_SCALE)
    )


def create_undistort_maps(
    calibration: Dict[str, object],
    frame_size: Tuple[int, int],
    balance: float,
    focal_scale: Optional[float] = None,
    projection_alpha: float = 1.0,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Create cached remap matrices for real-time undistortion.

    For fisheye cameras, ``balance=0`` uses the calibrated focal length for a
    natural, reference-like result. Increasing balance progressively widens
    the view down to the project's previous 0.70 focal scale. In addition,
    ``projection_alpha=1`` is the standard rectilinear projection; values
    below 1 progressively compress the image periphery.
    """

    width, height = int(frame_size[0]), int(frame_size[1])
    camera_matrix = np.asarray(calibration["K"], dtype=np.float64)
    distortion = np.asarray(calibration["D"], dtype=np.float64)
    model = str(calibration.get("model", "fisheye"))

    calibrated_size = calibration.get("image_size")
    if calibrated_size and len(calibrated_size) == 2:
        calibrated_width = float(calibrated_size[0])
        calibrated_height = float(calibrated_size[1])
        if calibrated_width > 0 and calibrated_height > 0:
            scale_x = width / calibrated_width
            scale_y = height / calibrated_height
            camera_matrix = camera_matrix.copy()
            camera_matrix[0, 0] *= scale_x
            camera_matrix[0, 2] *= scale_x
            camera_matrix[1, 1] *= scale_y
            camera_matrix[1, 2] *= scale_y

    if model == "fisheye":
        distortion = distortion.reshape(-1, 1)
        selected_focal_scale = (
            fisheye_focal_scale_for_balance(balance)
            if focal_scale is None
            else float(focal_scale)
        )
        if selected_focal_scale <= 0:
            raise ValueError("鱼眼矫正 focal_scale 必须大于 0。")
        projection_alpha = float(projection_alpha)
        if not 0.5 <= projection_alpha <= 1.0:
            raise ValueError("鱼眼投影 projection_alpha 必须在 [0.5, 1.0] 内。")
        new_camera_matrix = camera_matrix.copy()
        new_camera_matrix[0, 0] *= selected_focal_scale
        new_camera_matrix[1, 1] *= selected_focal_scale
        if projection_alpha >= 1.0 - 1e-9:
            map_x, map_y = cv2.fisheye.initUndistortRectifyMap(
                camera_matrix,
                distortion,
                np.eye(3),
                new_camera_matrix,
                (width, height),
                cv2.CV_32FC1,
            )
        else:
            output_y, output_x = np.indices((height, width), dtype=np.float64)
            normalized_x = (
                output_x - new_camera_matrix[0, 2]
            ) / new_camera_matrix[0, 0]
            normalized_y = (
                output_y - new_camera_matrix[1, 2]
            ) / new_camera_matrix[1, 1]
            output_radius = np.hypot(normalized_x, normalized_y)
            theta = np.arctan(projection_alpha * output_radius) / projection_alpha
            theta_squared = theta * theta
            coefficients = distortion.reshape(-1)
            distorted_theta = theta * (
                1.0
                + coefficients[0] * theta_squared
                + coefficients[1] * theta_squared**2
                + coefficients[2] * theta_squared**3
                + coefficients[3] * theta_squared**4
            )
            inverse_radius = np.divide(
                1.0,
                output_radius,
                out=np.zeros_like(output_radius),
                where=output_radius > 1e-12,
            )
            map_x = (
                camera_matrix[0, 2]
                + camera_matrix[0, 0]
                * distorted_theta
                * normalized_x
                * inverse_radius
            ).astype(np.float32)
            map_y = (
                camera_matrix[1, 2]
                + camera_matrix[1, 1]
                * distorted_theta
                * normalized_y
                * inverse_radius
            ).astype(np.float32)
            center_mask = output_radius <= 1e-12
            map_x[center_mask] = float(camera_matrix[0, 2])
            map_y[center_mask] = float(camera_matrix[1, 2])
    else:
        new_camera_matrix, _ = cv2.getOptimalNewCameraMatrix(
            camera_matrix,
            distortion,
            (width, height),
            balance,
            (width, height),
        )
        map_x, map_y = cv2.initUndistortRectifyMap(
            camera_matrix,
            distortion,
            None,
            new_camera_matrix,
            (width, height),
            cv2.CV_32FC1,
        )

    return map_x, map_y, new_camera_matrix


def create_balance_crop_roi(
    calibration: Dict[str, object],
    map_x: np.ndarray,
    map_y: np.ndarray,
    frame_size: Tuple[int, int],
    balance: float,
) -> Tuple[int, int, int, int]:
    """Return a centered crop between the no-black-border ROI and full view.

    ``balance=0`` selects the largest centered rectangle containing only valid
    fisheye pixels. ``balance=1`` returns the complete undistorted frame.
    """

    width, height = int(frame_size[0]), int(frame_size[1])
    balance = float(np.clip(balance, 0.0, 1.0))
    valid = create_undistort_valid_mask(
        calibration,
        map_x,
        map_y,
        frame_size,
    )
    invalid_integral = cv2.integral((~valid).astype(np.uint8))

    def centered_rectangle(scale: float) -> Tuple[int, int, int, int]:
        rectangle_width = max(1, int(round(width * scale)))
        rectangle_height = max(1, int(round(height * scale)))
        left = (width - rectangle_width) // 2
        top = (height - rectangle_height) // 2
        return left, top, left + rectangle_width, top + rectangle_height

    def invalid_count(rectangle: Tuple[int, int, int, int]) -> int:
        left, top, right, bottom = rectangle
        return int(
            invalid_integral[bottom, right]
            - invalid_integral[top, right]
            - invalid_integral[bottom, left]
            + invalid_integral[top, left]
        )

    low, high = 0.05, 1.0
    for _ in range(24):
        middle = (low + high) / 2.0
        if invalid_count(centered_rectangle(middle)) == 0:
            low = middle
        else:
            high = middle

    valid_left, valid_top, valid_right, valid_bottom = centered_rectangle(low)
    left = int(round(valid_left * (1.0 - balance)))
    top = int(round(valid_top * (1.0 - balance)))
    right = int(round(valid_right + (width - valid_right) * balance))
    bottom = int(round(valid_bottom + (height - valid_bottom) * balance))

    left = int(np.clip(left, 0, width - 1))
    top = int(np.clip(top, 0, height - 1))
    right = int(np.clip(right, left + 1, width))
    bottom = int(np.clip(bottom, top + 1, height))
    return left, top, right - left, bottom - top


def create_undistort_valid_mask(
    calibration: Dict[str, object],
    map_x: np.ndarray,
    map_y: np.ndarray,
    frame_size: Tuple[int, int],
) -> np.ndarray:
    """Return the valid source-pixel mask for a full undistorted frame."""

    width, height = int(frame_size[0]), int(frame_size[1])
    camera_matrix = np.asarray(calibration["K"], dtype=np.float64).copy()

    calibrated_size = calibration.get("image_size")
    if calibrated_size and len(calibrated_size) == 2:
        calibrated_width = float(calibrated_size[0])
        calibrated_height = float(calibrated_size[1])
        if calibrated_width > 0 and calibrated_height > 0:
            scale_x = width / calibrated_width
            scale_y = height / calibrated_height
            camera_matrix[0, 2] *= scale_x
            camera_matrix[1, 2] *= scale_y

    valid = (
        (map_x >= 0)
        & (map_x < width)
        & (map_y >= 0)
        & (map_y < height)
    )

    center_x = float(camera_matrix[0, 2])
    center_y = float(camera_matrix[1, 2])
    if str(calibration.get("model", "fisheye")) == "fisheye":
        valid_radius = 0.99 * min(
            center_x,
            width - 1 - center_x,
            center_y,
            height - 1 - center_y,
        )
        if valid_radius > 0:
            valid &= (
                (map_x - center_x) ** 2 + (map_y - center_y) ** 2
                <= valid_radius**2
            )
    return valid


def format_calibration_result(result: Dict[str, object]) -> str:
    camera_matrix = np.asarray(result["K"], dtype=np.float64)
    distortion = np.asarray(result["D"], dtype=np.float64).reshape(-1)
    model_name = "鱼眼（OpenCV Fisheye）" if result.get("model") == "fisheye" else "针孔（OpenCV）"
    image_size = result.get("image_size", ["?", "?"])
    board = result.get("board") or {}
    pattern_type = str(board.get("pattern_type", "charuco"))
    pattern_name = "传统黑白棋盘格" if pattern_type == "chessboard" else "ChArUco"

    lines = [
        f"模型：{model_name}",
        f"标定板：{pattern_name}",
        f"图像分辨率：{image_size[0]} × {image_size[1]}",
        f"有效标定图片：{result.get('images_used', '?')} 张",
        f"自动剔除异常图片：{len(result.get('outlier_images', []))} 张",
        f"RMS 重投影误差：{float(result.get('rms', 0.0)):.6f} px",
        f"平均单视图误差：{float(result.get('mean_reprojection_error', 0.0)):.6f} px",
        "",
        "相机内参矩阵 K：",
        np.array2string(camera_matrix, precision=8, suppress_small=False),
        "",
        "畸变系数 D：",
        np.array2string(distortion, precision=10, suppress_small=False),
        "",
        f"fx={camera_matrix[0, 0]:.8f}",
        f"fy={camera_matrix[1, 1]:.8f}",
        f"cx={camera_matrix[0, 2]:.8f}",
        f"cy={camera_matrix[1, 2]:.8f}",
        "",
        "COLMAP 参数：",
        str(result.get("colmap") or build_colmap_camera_line(
            str(result.get("model", "fisheye")),
            camera_matrix,
            distortion,
        )),
    ]

    outlier_images = result.get("outlier_images") or []
    if outlier_images:
        lines.extend(["", "已自动剔除的误差离群图片："])
        lines.extend(
            f"{item['name']}  初次误差={float(item['initial_error']):.6f} px"
            for item in outlier_images
        )

    skipped = result.get("skipped_images") or []
    if skipped:
        lines.extend(["", f"跳过的图片：{len(skipped)} 张", *map(str, skipped)])
    return "\n".join(lines)
